replicas: 1

namespace: webhooks
resources: {}
secrets:
  create: false # Indicates if the secret should be created (can be false if the secret already exists)
  tls_crt: ""
  tls_key: ""

tolerations: []

serviceAccount: {}
  # create: true
  # name: ""

# certsExistingSecretName: test

webhook:
  rules:
    - operations: [""]
      apiGroups: [""]
      apiVersions: ["*"]
      resources: [""]
      scope: "*"
  timeoutSeconds: 5
  # annotations:
  #   cert-manager.io/inject-ca-from: "webhooks/example"
  # podAnnotations:
  #   reloader.stakater.com/auto: "true"
  containerImage: "gcr.io/cloudkite-public/custom-mutating-webhook:multi-patch"

env:
  PATCH_DICT: ""
  MATCH_NAMESPACES: ""
